### ISSUE TITLE
error installing on Windows 10

### ISSUE THREAD

**Issue by rkamarowski** [coleifer/unqlite-python#11]
Received the following error when attempting to install in Python34\Lib\ folder:

 Directory of C:\Python34\Lib\unqlite-python-master

08/08/2015  01:44 PM    <DIR>          .
08/08/2015  01:44 PM    <DIR>          ..
08/08/2015  01:44 PM    <DIR>          docs
08/08/2015  01:44 PM             1,058 LICENSE
08/08/2015  01:44 PM               223 MANIFEST.in
08/08/2015  01:44 PM             7,412 README.md
08/08/2015  01:44 PM               762 setup.py
08/08/2015  01:44 PM    <DIR>          src
08/08/2015  01:44 PM            15,364 tests.py
08/08/2015  01:44 PM           951,341 unqlite.c
08/08/2015  01:44 PM            39,819 unqlite.pyx
               7 File(s)      1,015,979 bytes
               4 Dir(s)  626,046,054,400 bytes free

C:\Python34\Lib\unqlite-python-master>pip install unqlite
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting unqlite
  Using cached unqlite-0.4.1.tar.gz
    C:\Users\Bob\AppData\Local\Temp\pip-build-__uoexdg\unqlite\setup.py:9: UserW
arning: Cython not installed, using pre-generated C source file.
      warnings.warn('Cython not installed, using pre-generated C source file.')
Installing collected packages: unqlite
  Running setup.py install for unqlite
    building 'unqlite' extension
    C:\Users\Bob\AppData\Local\Temp\pip-build-__uoexdg\unqlite\setup.py:9: UserW
arning: Cython not installed, using pre-generated C source file.
      warnings.warn('Cython not installed, using pre-generated C source file.')
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    Complete output from command C:\Python34\python.exe -c "import setuptools, t
okenize;__file__='C:\\Users\\Bob\\AppData\\Local\\Temp\\pip-build-__uoexdg\\unql
ite\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().rep
lace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Bob\AppData\Lo
cal\Temp\pip-zz_9rkjb-record\install-record.txt --single-version-externally-mana
ged --compile:
    running install

    running build

    running build_ext

    building 'unqlite' extension

    C:\Users\Bob\AppData\Local\Temp\pip-build-__uoexdg\unqlite\setup.py:9: UserW
arning: Cython not installed, using pre-generated C source file.

      warnings.warn('Cython not installed, using pre-generated C source file.')

    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

    ----------------------------------------
    Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:
\\Users\\Bob\\AppData\\Local\\Temp\\pip-build-__uoexdg\\unqlite\\setup.py';exec(
compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'),
__file__, 'exec'))" install --record C:\Users\Bob\AppData\Local\Temp\pip-zz_9rkj
b-record\install-record.txt --single-version-externally-managed --compile" faile
d with error code 1 in C:\Users\Bob\AppData\Local\Temp\pip-build-__uoexdg\unqlit
e

C:\Python34\Lib\unqlite-python-master>

**Comment by coleifer** [comment]
I do not have plans to support windows or python 3.x.

**Comment by rkamarowski** [comment]
Thank you for the information. Do you know of anyone who is writing bindings for 3.4?

 

Bob K.
