### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Johnathon332** [coleifer/unqlite-python#18]
I tried to add a collection of metrics to a collection but got a segmentation fault.  I am using unqlite on a test.udb file and writing every result to that file if there is a connection error or exception.

Here is my code:

```python
def AddToLocalDB(list):
	with UnQLite('/home/pi/test.udb') as db:
            collection = db.collection('pending')
            collection.create()
            collection.exists()
            collection.store(list)
```

I am passing this a list.

**Comment by coleifer** [comment]
I ran this locally without issue. Can you use gdb or similar to get a backtrace? What is the content of the list, as well.
