### ISSUE TITLE
Boolean functionality seems "off"

### ISSUE THREAD

**Issue by atonkyra** [coleifer/unqlite-python#23]
From the API docs you get the idea that unqlite can support booleans. However I'm getting this result

```
>>> from unqlite import UnQLite
>>> db = UnQLite()
>>> db.collection('test').create()
>>> db.collection('test').store({'booltest': False,'another': True})
>>> db.collection('test').all()
[{'booltest': 0, '__id': 0, 'another': 1}]
>>> db['anothertest'] = True
>>> db['anothertest']
'True'
>>> type(db['anothertest'])
<type 'str'>
```

Tested with unqlite (0.5.2) and Python 2.7.6

**Comment by coleifer** [comment]
Hmm... weird yeah. I'll look into it, thanks.

**Comment by coleifer** [comment]
I had a sneaking suspicion after looking at the code that this might be the issue...

```python
>>> isinstance(True, int)
True
```

I moved the test for bool above int and it's fixed.

Regarding the KV interface -- i.e., db['foo'] = True ... db['foo'] -> 'True' -- this is expected. The KV interface only cares about bytes. The collection interface is Jx9 which stores type information as well, but that is completely separate.

**Comment by atonkyra** [comment]
Thanks!
