### ISSUE TITLE
Cython dependency fails pip install

### ISSUE THREAD

**Issue by akangasr** [coleifer/unqlite-python#30]
Expectation:
Adding both `cython` and `unqlite` to a pip requirements.txt will install both libraries.

Issue:
If the package is installed with pip, the installation may fail unless Cython is explicitly installed first (ie. you first run `pip install cython` and only after that install the rest of the requirements). It appears that this dependency is not specified explicitly and thus pip can not reason about installation order.

**Comment by coleifer** [comment]
I have specified "install_requires=['cython']" in the setup.py for the project. I am not sure what you mean by the dependency not being specified explicitly.

**Comment by akangasr** [comment]
It really seems to be set up so in setup.py. However, when I try to install with pip, it outputs:

$ pip install cython unqlite
Collecting cython
  Using cached Cython-0.25.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting unqlite
  Using cached unqlite-0.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d4IuN0/unqlite/setup.py", line 7, in <module>
        raise RuntimeError('Cython must be installed to build unqlite-python.')
    RuntimeError: Cython must be installed to build unqlite-python.

Maybe the issue is that executing the setup.py itself already requires cython?

If I would be installing the lib independently, it would be easy to first install cython, then unqlite, but when the library is among many dependencies of a larger project, it is cumbersome to define these kind of exceptions.

**Comment by fbigun** [comment]
Installed after the first installation of unixite cython on it.

on linux
```
pip install cython
pip install unqlite
```

**Comment by fbigun** [comment]
@coleifer Can directly support the binary package on windows...

**Comment by alexmozzhakov** [comment]
AttributeError: class Extension has no attribute '__mro__'
    Command "python setup.py egg_info" failed with error code 1 in /private/var/... 
appears on macOS when trying to install using pip.

**Comment by alexmozzhakov** [comment]
Seems to work only on python 3.x. Please double check you're using correct version of pip by running `pip3 -V`

**Comment by coleifer** [comment]
126803cda7f9d05710021488bf0f5039104eebd6

**Comment by coleifer** [comment]
Added it as `setup_requires=['cython']` in addition to `install_requires` in the `setup()` function.

**Comment by alexmozzhakov** [comment]
@coleifer works on my machine. I think you can close an issue
