### ISSUE TITLE
pass primary key manually

### ISSUE THREAD

**Issue by haehn** [coleifer/unqlite-python#33]
Specifying `__id` manually is not supported in the python bindings.

```
    collection.store({
        '__id': 12345
    })
```

Then

```
    collection.all()
```

returns

```
[{'__id':0}]
```

It seems that the C++ interface supports a key argument (https://unqlite.org/c_api/unqlite_kv_store.html).

**Comment by coleifer** [comment]
The collections are different from the KV interface.

**Comment by haehn** [comment]
Is there a way to specify `__id`?

**Comment by haehn** [comment]
@thejohnhoffer

**Comment by coleifer** [comment]
Why would you need to?

**Comment by haehn** [comment]
we have a list of synapses with neuron_id1 and neuron_id2. we loop through the list and insert synapses into a collection. but we also want to insert each neuron into a collection with its id as a primary key.

right now we would have to insert a separate fake-primary key field (neuron_id) and maintain uniqueness etc. it would be much better if we could just set __id
