### ISSUE TITLE
Collections store None instead of numpy numbers

### ISSUE THREAD

**Issue by thejohnhoffer** [coleifer/unqlite-python#34]
Hi! 
This problem arises because [numpy numbers][0] and [python numbers][1] have different datatypes. Specifically, I've noticed that __unqlite collections__ work fine with values of type `int`, but they fail to store values of type `numpy.uint8`.

- I can `collection.store` dictionaries that look like this:
```
{'VI': 2, 'V': 1, 'VII': 3, 'IV': 0}
```
- The collections object stores the values:
    - _Correctly_ if the values are of type`int`
    - __Not at all__ (all as `None`) if the values are of type`np.uint8`
        - or _any numpy type_ such as uint16, int64, float32, etc

## A real `numpy.uint8` test case runs like this
```python
import unqlite
import numpy as np
# Ignore this until I've made my point
from fancy_log_example import log

# Create in-memory database
mem_db = unqlite.UnQLite(':mem:')
collect = mem_db.collection('mem0')
collect.create()

# Store to mem_db collection
def store(keys, values):
    # Store keys and values as a dict
    entry = dict(zip(keys,values))
    print '    Storing:', entry
    # Store dict in your collection
    collect.store(entry)
    # defined below
    log(collect)

# Starwars keys and values
starwars_keys = ['IV','V','VI','VII']
starwars_values = [0, 1, 2, 3]

print 'Successfully store with int values:'
store(starwars_keys, starwars_values)

print 'Fail to store with numpy.uint8 values:'
store(starwars_keys, np.uint8(starwars_values))
```

## The log shows the __Main Issue__ and a potentially related _Side Note_:
```regex
Successfully store with int values:
    Storing: {'VI': 2, 'V': 1, 'VII': 3, 'IV': 0}
    Great values: [0, 1, 2, 3]
Fail to store with numpy.uint8 values:
    Storing: {'VI': 2, 'V': 1, 'VII': 3, 'IV': 0}
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
..............
AssertionError: 
    Main Issue: values [None, None, None, None] for last id 1
    Side Note: current id is somehow still 0
```

******

- Finally, here's `fancy_log_example.py` so you can see
    - The values from log only come from legitimate uses of your API
    - I just `assert` expected behavior that `any` values are stored in the collection

```python
def log(collect):
    # Get "last record" and "current record"
    last = collect.fetch(collect.last_record_id())
    current = collect.fetch_current()
    # Side Note: the current and last ids differ
    new_ids = last.pop('__id'), current.pop('__id')

    # Main Issue: ALL the added values have no value.
    added = sorted(last.values())
    assert any(added), '''
    Main Issue: values {} for last id {}
    Side Note: current id is somehow still {}
    '''.format(added, *new_ids)
    # Values are great for python int
    print '    Great values:', added
```

[0]: https://docs.scipy.org/doc/numpy/user/basics.types.html
[1]: https://docs.python.org/2.4/lib/typesnumeric.html

******

Please take time to respond to this. I can help you find out where to best fix this in your codebase if you only have time to supply a first impression of where `Collection` may be going wrong in storing numpy datatypes. Numpy ints or floats in particular __are very useful__ for optimization as they are always a fixed number of bytes. You may find [this particular method][2] `numpy.ndarray.tostring` useful for writing these such values to the database. 

Example:

```python
print np.uint32(1).tobytes()
# prints '\x01\x00\x00\x00'
```

Thanks for your time!

[2]: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tostring.html

**Comment by coleifer** [comment]
Why can't you just coerce these numpy values to regular Python objects? The issue is probably here:

```cython
cdef python_to_unqlite_value(VM vm, unqlite_value *ptr, python_value):
    cdef unqlite_value *item_ptr = <unqlite_value *>0
    cdef bytes encoded_value

    if isinstance(python_value, unicode):
        encoded_value = python_value.encode('utf-8')
        unqlite_value_string(ptr, encoded_value, -1)
    elif isinstance(python_value, bytes):
        unqlite_value_string(ptr, python_value, -1)
    elif isinstance(python_value, (list, tuple)):
        for item in python_value:
            item_ptr = vm.create_value(item)
            unqlite_array_add_elem(ptr, NULL, item_ptr)
            vm.release_value(item_ptr)
    elif isinstance(python_value, dict):
        for key, value in python_value.items():
            if not isinstance(key, basestring):
                key = str(key)
            if isinstance(key, unicode):
                key = key.encode('utf-8')
            item_ptr = vm.create_value(value)
            unqlite_array_add_strkey_elem(
                ptr,
                <const char *>key,
                item_ptr)
            vm.release_value(item_ptr)
    elif isinstance(python_value, bool):
        unqlite_value_bool(ptr, python_value)
    elif isinstance(python_value, (int, long)):
        unqlite_value_int64(ptr, python_value)
    elif isinstance(python_value, float):
        unqlite_value_double(ptr, python_value)
    else:
        unqlite_value_null(ptr)
```

I'd need to add checks for all the numpy types, which is not really something I'm interested in doing.

**Comment by thejohnhoffer** [comment]
Hi! Well, at some point I would like to have `np.uint64` values, which based on the code above would overflow at 2^63 in your system due to a coercion to signed integer 64.

**Comment by thejohnhoffer** [comment]
Then there's the additional point that anyone storing values only from 0-255 will be using eight times as much memory/disk space as needed for their `np.uint8` stored as `int64`

**Comment by thejohnhoffer** [comment]
In my current use case, I would like to store many millions of uint32 values. I know four bytes is always enough. Your database is currently making me to use twice as much memory and disk space as needed by coercing everything to int64.

**Comment by thejohnhoffer** [comment]
If you could reopen this issue, I can start work on a pull request to properly account for numpy types.

**Comment by coleifer** [comment]
I'm not necessarily interested in supporting the numpy types. Additionally, I think unqlite uses 64-bit integers on the backend anyways, for all integers.
