### ISSUE TITLE
Slow performance when dropping collection

### ISSUE THREAD

**Issue by efficks** [coleifer/unqlite-python#38]
Python 3.6.3
unqlite 0.6.0
-----
I've create a collection with 10,000 entries. When starting the application, I need to clear the collection and I'm using drop() to do so.

The db is about 25 Mib. But it takes forever to do the drop. I don't know exactly how many times because I always kill it before it reach the end but the last time I've kill it after 10 minutes.
During this time, one CPU is used at 100%. I'm unable to do a CTRL+C, I need the kill the process.
Inserting the records in a fresh db only took me seconds.
Why is it so slow?

``` python
with db.transaction():
        if __collPlanip.exists():
            __collPlanip.drop() # it blocks here
        __collPlanip.create()

```

**Comment by coleifer** [comment]
Have you tried profiling, debugging or anything? I ran a test locally and was able to create a collection that was over 100MB and it dropped reasonably quickly.

**Comment by efficks** [comment]
@coleifer I've not tried any of these options. I've found nothing in the doc to debug it.

**Comment by coleifer** [comment]
You might try using gdb.
