### ISSUE TITLE
fetch() return a dict with binary values contrary to example

### ISSUE THREAD

**Issue by mylese** [coleifer/unqlite-python#42]
The example given returns binary values (for me):

    >>> users.store({'name': 'Leslie', 'color': 'also green'})
    0
    >>> users.fetch(0)
    {'name': b'Leslie', 'color': b'also green', '__id': 0}

**Comment by coleifer** [comment]
I probably ran the example using Python 2.x.

**Comment by mylese** [comment]
Yes, I'm on 3.x, I'm not sure if this is an issue or not now, closing just in case.

**Comment by zoopp** [comment]
This issue is easily reproducible using the following code:

```python
Python 3.6.5 (default, May 11 2018, 04:00:52) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import unqlite
   ...: 
   ...: db = unqlite.UnQLite()
   ...: collection = db.collection('users')
   ...: collection.create()
   ...: 
   ...: user_id = collection.store({'name': 'Johnson'})
   ...: collection.fetch(user_id)
   ...: 
   ...: 
{'name': b'Johnson', '__id': 0}
```

I'm not sure I understand, is this regarded as acceptable 3.x behavior? If so then this does not look right to me.

**Comment by coleifer** [comment]
It's not a bug, this is expected behavior -- data is stored as bytestrings.

**Comment by zoopp** [comment]
Internal storage representation aside, the way the provided interface works is the one that strikes me as odd. Some values when marshaled/unmarshaled keep their correct type but a string type is treated differently. Take a look at the following example:

```python3
import unqlite

db = unqlite.UnQLite()
collection = db.collection('users')
collection.create()

name, age, height = 'Johnson', 34, 2.4
friends = ['Alex', 'Maria']
phone_numbers = [123112, 2255223, 223131345]

user_id = collection.store({
    'name': name,
    'age': age,
    'height': height,
    'friends': friends,
    'phone_numbers': phone_numbers
})
user = collection.fetch(user_id)

print(user)
print(type(name), type(age), type(height), type(friends), type(phone_numbers))
print(type(user['name']), type(user['age']), type(user['height']),
      type(user['friends']), type(user['phone_numbers'])) 
```
.. which yields the following output:
```python
{'name': b'Johnson', 'age': 34, 'height': 2.4, 'friends': [b'Alex', b'Maria'], 'phone_numbers': [123112, 2255223, 223131345], '__id': 0}
<class 'str'> <class 'int'> <class 'float'> <class 'list'> <class 'list'>
<class 'bytes'> <class 'int'> <class 'float'> <class 'list'> <class 'list'>
```

`int`, `float` and `list` are unmarshalled as their respective types, wouldn't you normally expect a string to be unmarshalled as its respective type as well?

**Comment by coleifer** [comment]
> wouldn't you normally expect a string to be unmarshalled as its respective type as well?

How do you know the difference between a utf8-encoded text string and a raw binary bytestring? Keys are considered text, hence they are decoded, but values are treated as opaque bytes.

**Comment by zoopp** [comment]
> Keys are considered text, hence they are decoded, but values are treated as opaque bytes.

I see. I'm not too familiar with UnQLite itself so I should have read the docs beforehand. Thanks for clearing that up, it makes sense now.
