### ISSUE TITLE
collection fetch, anyway it will return a value

### ISSUE THREAD

**Issue by yingsf** [coleifer/unqlite-python#43]
unqlite==0.7.0

Python 3.6.5 (default, Jun 17 2018, 12:13:06)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

```python
>>> from unqlite import UnQLite
>>> db = UnQLite()
>>> demo = db.collection('demo')
>>> demo.create()
>>> demo.store({"one":1})
0
>>> demo.fetch(0)
{'one': 1, '__id': 0}
>>> demo.fetch('0')
{'one': 1, '__id': 0}
>>> demo.fetch('0xxx')
{'one': 1, '__id': 0}
```

**Comment by coleifer** [comment]
Has something to do with how UnQLite reads integers.
