### ISSUE TITLE
Update db entry in multiple threads

### ISSUE THREAD

**Issue by avocadochicken** [coleifer/unqlite-python#44]
Hello! Can anyone explain to me how to upgrade database entries in parallel? I have a db file opened in one process that needs to iterate over all entries while updating with a certain key (different values) if not already existent. I need a few hundred concurrent threads.

```
#!/usr/bin/python3

from unqlite import UnQLite
from concurrent.futures import ThreadPoolExecutor

db = UnQLite('tmp.db')
coll = db.collection('coll')
coll.create()

def fill_db():
    global coll
    for i in range(10):
        s = dict()
        s['id'] = i
        s['flag'] = True
        coll.store(s)

def show_db():
    global coll
    for i in range(len(coll)):
        s = coll.fetch(i)
        print('entry', i, '=>', s)

def upd(idx):
    global coll
    print('Working on', idx)
    c = coll.fetch(idx)
    c['other'] = 1
    if not c.update(idx, c):
        print('Error during update', idx)
    else:
        coll.commit()

def update_db():
    global coll

    with ThreadPoolExecutor(max_workers=2) as pool:
        for i in range(len(coll)):
            if 'other' in coll[i].keys():
                continue
            
            # update each item if key 'other' is not yet present
            pool.submit(upd, i)

        print('Done!')
        pool.shutdown(wait=True)

if __name__ == '__main__':
    fill_db()
    show_db()
    update_db()
    show_db()

    db.close()
```

Python 3.6.5
I can not find the __ version __ string for unqlite. But the filename is: unqlite.cpython-36m-i386-linux-gnu.so

**Comment by coleifer** [comment]
Is an error or something happening?

For what it's worthy, if you're trying to parallel-ize the actual updating of the database, I don't think you're going to see any benefit over single-threaded. UnQLite is embedded in the Python process and there's no socket I/O operations that would make for good places to do context-switching.

**Comment by coleifer** [comment]
It looks like UnQLite is not thread-safe by default. Check out the "Compile-Time Options" section of the docs:

https://unqlite.org/c_api_const.html

**Comment by avocadochicken** [comment]
My posted code runs without any unhandled exception thrown. I guess there is no error, but there is no update at all, i.e. not a single database entry gets updated.
I choose this DB, because http://unqlite-python.readthedocs.io/en/latest/index.html states it is thread safe. I need several hundred / thousands concurrent threads. It is not about the speed up, but about different connections that receive timeouts/data on different times.

**Comment by coleifer** [comment]
You're best off probably using a single dedicated thread for writing to the UnQLite database. You can use a queue to have the worker threads push updates to the writer thread...I think that will probably work much better for you.

**Comment by avocadochicken** [comment]
Of course.
Maybe the thread safety info should be removed from the docs?

**Comment by coleifer** [comment]
I pulled it right from the UnQLite official document on their homepage. It says thread-safe and fully re-entrant. I've created an issue symisc/unqlite#71 which should hopefully clarify.
