### ISSUE TITLE
Question about multithread

### ISSUE THREAD

**Issue by xiaoch05** [coleifer/unqlite-python#45]
I install unqlite using "pip install unqlite" command. But such codes generate a file named "test.db_unqlite_journal" and data cannot be written into the file "test.db". If the line 'timer.start()' is deleted, then it works well. Cannot unqlite be used in multithread environment?

```
from threading import Thread
from unqlite import UnQLite
import time

class Timer(Thread):
    def run(self):
        while True:
            time.sleep(1)

db = UnQLite("test.db")
users = db.collection("users")
users.create()
users.store({'name':'Tom', 'age':23})

timer = Timer()
timer.start()

time.sleep(1000)
```

**Comment by coleifer** [comment]
> Cannot unqlite be used in multithread environment?

I'd suggest asking on https://unqlite.org/forum/ -- I'm not sure what your code is trying to do, by the way, it just writes to the collection and sleeps?

**Comment by xiaoch05** [comment]
@coleifer thanks, this is just a test code, a thread just doing nothing can effect the collection. I have solved by executing 'db.commit()'
