### ISSUE TITLE
Flags unavailable via Python

### ISSUE THREAD

**Issue by fonaro** [coleifer/unqlite-python#47]
I could not access the open flags via the Python implementation:
- UNQLITE_OPEN_CREATE
- UNQLITE_OPEN_READONLY
- UNQLITE_OPEN_READWRITE
- UNQLITE_OPEN_CREATE
- UNQLITE_OPEN_EXCLUSIVE
- UNQLITE_OPEN_TEMP_DB
- UNQLITE_OPEN_NOMUTEX
- UNQLITE_OPEN_OMIT_JOURNALING
- UNQLITE_OPEN_IN_MEMORY
- UNQLITE_OPEN_MMAP

They are defined as `cdef` in `unqlite.pyx`. Should they be defined as `cpdef`?

**Comment by coleifer** [comment]
Making them `cpdef` does not change the fact that they are not exported into the python module namespace. They would need to be declared separately.

**Comment by coleifer** [comment]
Well, for now I'll suggest just defining them in your code. I've asked about this before and not really received a satisfactory (to my thinking) answer:

https://stackoverflow.com/questions/31766219/export-constants-from-header-with-cython
