### ISSUE TITLE
AsyncIO Support?

### ISSUE THREAD

**Issue by techdragon** [coleifer/unqlite-python#51]
It would be quite handy if this supported `async`/AsyncIO in newer versions of python... assuming that the necessary features already exist in unqlite of course :smile:

**Comment by coleifer** [comment]
![](http://media.charlesleifer.com/playground/notes/img/welfin-1.png)

It's an embedded database... there's no socket i/o at all. What do you even...

**Comment by techdragon** [comment]
@coleifer Just because it's an embedded database, doesn't mean its not blocking. SQLite is an embedded database with no sockets in sight, but we have https://github.com/jreese/aiosqlite to provide non-blocking AsyncIO support for it. AsyncIO isn't just for network/socket related I/O.

**Comment by coleifer** [comment]
Yes and I have real questions about the utility of aiosqlite. It is really just a compatibility layer and in no way geared towards performance.

**Comment by coleifer** [comment]
If you look at the code/issues you can see all kinds of bullshit about inserting sleeps and queue timeouts...it's garbage.

**Comment by techdragon** [comment]
@coleifer Thanks for the clarification. I've only just started to dig into using AsyncIO, I assumed the library would be using https://www.sqlite.org/asyncvfs.html and be 'properly' asynchronous, and wasn't sure if unqlite had an equivalent. Having looked at unqlite more now though I'm not sure it has an equivalent async feature, also looking at aiosqlite a bit more deeply, i can already see what you were talking about.
