### ISSUE TITLE
ValueError when inserting to nonexistent collection

### ISSUE THREAD

**Issue by buckle2000** [coleifer/unqlite-python#53]
```
db = UnQLite()
users = db.collection('users')
users.store({'a': 0})

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
unqlite.pyx in unqlite.Collection._simple_execute()

unqlite.pyx in unqlite.VM.__getitem__()

unqlite.pyx in unqlite.VM.get_value()

KeyError: 'ret'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-36-2102913e9c8f> in <module>
----> 1 users.store({'a': 0}) # ValueError

unqlite.pyx in unqlite.Collection.store()

unqlite.pyx in unqlite.Collection._simple_execute()

unqlite.pyx in unqlite.Collection._simple_execute()

ValueError: Error fetching return value from script.
```

This error is not descriptive.

**Comment by coleifer** [comment]
The fact that it raises an exception is enough for me right now. You can write your own Jx9 scripts and execute them if you would like to try and add more robust error handling. Note that the jx9 error-handling facilities are fairly limited.

The unqlite library is not being very actively developed and my opinion is that it is really a bad choice for any new code. In the `README` for this project I strongly suggest you read the symisc issue tracker before deciding to use unqlite.

You will be *much* better served using sqlite.

**Comment by buckle2000** [comment]
Thanks!
