### ISSUE TITLE
collection.store returs int

### ISSUE THREAD

**Issue by buckle2000** [coleifer/unqlite-python#54]
```
db = UnQLite()
users = db.collection('users')
users.store([{'a':3}]) # 0
```
It's not a boolean, as described [here](https://unqlite.org/jx9_func/db.html#db_store).

**Comment by coleifer** [comment]
You're looking at the wrong documentation. This is the documentation for the python library:

https://unqlite-python.readthedocs.io/en/latest/api.html#Collection.store

By default it returns the id of the newly-added object.

**Comment by buckle2000** [comment]
Shouldn't the python API be the same as C API?
It says here too:
https://github.com/coleifer/unqlite-python/blame/master/README.md#L166-L175

**Comment by coleifer** [comment]
By default, unqlite-python returns the last-ID of the inserted object into the collection. You can get the "boolean" return value by specifying `return_id=False`. I've updated the README.
