### ISSUE TITLE
FR: Binary releases on PyPI

### ISSUE THREAD

**Issue by positron96** [coleifer/unqlite-python#56]
Hi. Could you please add binary wheels for pip, for widespread architectures and python versions?

Right now, installing unqlite via pip seems to require a C/C++ compiler, which can be problematic in some situations. I've stumbled upon this while trying to make a CI/CD chain for building a windows distributable of my application using a docker container with wine and pyinstaller. Stuffing MSVC inside is impossible, and stuffing MinGW requires a lot more that simple python knowledge.

**Comment by coleifer** [comment]
I don't have any plans to do this, but anyone is free to do so by registering the `unqlite-binary` package and providing wheels.

**Comment by positron96** [comment]
Hi, thank you for response.
Just for the sake of not creating extra entities on pypi, would you accept pull requests that build binaries automatically? I am not sure that it will work, but I may try.

**Comment by coleifer** [comment]
I package pysqlite3 and sqlcipher3 as wheels and the process is sufficiently complicated and annoying that I'm loth to agree to maintaining yet-another-wheel-package. Especially if it involves platforms outside of linux. I think if you are motivated then you can certainly register unqlite-binary, but I don't have the inclination to maintain it. Furthermore, unqlite itself (the underlying library) is not really actively developed anymore, and I strongly recommend people to just use sqlite.
