### ISSUE TITLE
Collection cursor only returns first record

### ISSUE THREAD

**Issue by anselor** [coleifer/unqlite-python#57]
Instead of fulling loading the entire collection into memory, I'd like to fetch one record at a time from a collection.
The API seems to indicate that the Collection object can behave like a cursor however it doesn't seem to work correctly.

`Collection.current_record_id()` seems to always return 0 no matter what. For example, I can store a record, delete it, and then store a new record. Record 0 shouldn't exist but then `current_record_id()` still reports 0.

`Collection.fetch_current()` always returns the first record in the collection. It behaves as if it doesn't advance the cursor. Looking at the implementation it looks like it just calls the jx9 `db_fetch()`. The unqlite documentation says that it should return the current document and then advance the cursor. I suspect what's happening is that it's a new cursor for each new VM instance and every call to Collection creates a new VM instance, compiles a new jx9 script, and runs it.

I tried this to test my theory and also see if I could work around the issue but I get a segfault trying to assign the `collection` variable on the VM instance:

```python

import unqlite

db = unqlite.UnQLite()
c1 = db.collection('c1')
c1.create()
c1.store([{'a':1}, {'b':2}, {'c':3}, {'d':4}])

vm = db.vm('$ret = db_fetch($collection);')
vm['collection'] = 'c1'  # <-- This line segfaults
vm.execute()
print(vm['ret'])
vm.execute()
print(vm['ret'])
```

**Comment by coleifer** [comment]
The jx9 vm is not kept around in memory when using those access methods and doing so would imply a pretty fundamental shift (plus I'm not quite sure it is even supported). I will take a look as I think you're correct about the cause for this behavior. Thanks for the report.

**Comment by coleifer** [comment]
Looking at this some more, I do not believe this will work as you are hoping. While it is possible to write a Jx9 script and do your iteration there, there does not seem to be a great way to repeatedly call into a Jx9 VM and ask it to "run one more time" - thus I don't think we can expose a Python iterator. We can write a Jx9 script and have it call a user-defined callback for each row, but that's already possible using the `filter()` method.

Your code wasn't working because you did not call `vm.compile()` by the way. It works for a single execution, but calling `execute()` a 2nd time complains about the collection not existing (??):

```python
In [2]: db = unqlite.UnQLite()                                                                  

In [3]: c1 = db.collection('c1')                                                                

In [4]: c1.create()                                                                             

In [5]: c1.store([{'k0': 0}, {'k1': 1}, {'k2': 2}])                                             
Out[5]: 2

In [6]: vm = db.vm('$ret = db_fetch($collection)')                                              

In [7]: vm.compile()                                                                            

In [8]: vm['collection'] = 'c1'                                                                 

In [9]: vm.execute()                                                                            

In [10]: print(vm['ret'])                                                                       
{'k0': 0, '__id': 0}

In [11]: vm.execute()                                                                           
---------------------------------------------------------------------------
UnQLiteError                              Traceback (most recent call last)
<ipython-input-11-064ef6d1b437> in <module>
----> 1 vm.execute()

unqlite.pyx in unqlite.VM.execute()

unqlite.pyx in unqlite.VM.execute()

unqlite.pyx in unqlite.UnQLite.check_call()

UnQLiteError: Collection 'c1' not defined in the underlying database
```

Overall I would strongly strongly suggest that you consider using Sqlite, which is actively maintained and supports all these different operations.

**Comment by coleifer** [comment]
I don't know, maybe it's possible that using the jx9 `vm_reset()` functionality and re-executing will provide the desired results -- but I'm not too sure. I'll look into it, and if so, will reopen as that will provide a way to implement the iterator interface.

**Comment by coleifer** [comment]
It turns out that the method I mentioned [here](https://github.com/coleifer/unqlite-python/issues/57#issuecomment-731834638) works correctly. I've implemented:

* `Collection.iterator()` -> returns an iterator over the collection
* `Collection.__iter__()` -> also allows iteration over the collection

These methods work by creating a small wrapper around a VM and then repeatedly calling `unqlite_vm_reset()` to re-execute a script that fetches the subsequent row.

**Comment by anselor** [comment]
@coleifer Thanks for the prompt response.

I just pulled down the latest and when I try it the iterator only returns the first element.

Here's what I'm seeing:
```
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import unqlite
>>> db = unqlite.UnQLite()
>>> c1 = db.collection('c1')
>>> c1.create()
>>> c1.store([{'k1':0}, {'k1':1}, {'k1':2}])
2
>>> len(c1)
3
>>> for item in c1:
...     print(item)
...
{'k1': 0, '__id': 0}
>>> c1iter = c1.iterator()
>>> for item in c1iter:
...     print(item)
...
{'k1': 0, '__id': 0}
>>> print(c1.all())
[{'k1': 0, '__id': 0}, {'k1': 1, '__id': 1}, {'k1': 2, '__id': 2}]
```

**Comment by anselor** [comment]
It looks like the issue is that `vm_reset()` is also resetting all of the assigned variables. I was able to reproduce it this way:

```
>>> vm = db.vm('$ret = db_fetch($collection);')
>>> vm.compile()
>>> vm['collection'] = 'c1'
>>> vm.execute()
>>> print(vm['ret'])
{'k1': 0, '__id': 0}
>>> vm.reset()
True
>>> vm.execute()
>>> print(vm['ret'])
None
>>> vm.reset()
True
>>> vm['collection'] = 'c1'
>>> vm.execute()
>>> print(vm['ret'])
{'k1': 1, '__id': 1}
>>>
```

**Comment by coleifer** [comment]
It was passing the tests I added and working, but not on 2.7 and 3.8+. The unqlite doc store document seems to indicate this is not necessary:

https://unqlite.org/api_intro.html#doc_store

But perhaps we're dropping a reference on the python side? I'm not sure.

**Comment by anselor** [comment]
It looks like the issue with the unit test is that the assertion is halting when either iterable runs out of items. When I add an assertion to check that there are 10 items returned by the iterator it fails. I've updated the test and verified adding the line seems to fix it.

**Comment by coleifer** [comment]
I don't believe that is correct.

**Comment by anselor** [comment]
On this line:
https://github.com/anselor/unqlite-python/blob/b89513c289c8ec882e074a45299142564d3f82ca/tests.py#L547

When I added `print(iter_items)` it only prints 1 item in the list and yet the assertion on following line, comparing the 2 lists evaluated to true. I had to line the assertion comparing the lengths to get the unit test to fail.

**Comment by anselor** [comment]
Oh, nevermind, that was before I noticed that test was being skipped on 3.8.

**Comment by coleifer** [comment]
For what it's worth, with the above patch I just added (cc0f9a9ab939c53cfbadac58e808ccb8bbbee76d) the tests are passing on 2.7 and 3.8.

**Comment by anselor** [comment]
@coleifer 
Pulled down the latest on master and can confirm it is now behaving as expected on my machine.

Also, as a sanity check, went ahead and created 2 iterator instances and verified that they can be independently iterated without any problems.

```
Python 3.8.2 (default, Jul 16 2020, 14:00:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import unqlite
>>> db = unqlite.UnQLite()
>>> c1 = db.collection('c1')
>>> c1.create()
>>> c1.store([{'k1':0}, {'k1':1}, {'k1':2}])
2
>>> for item in c1:
...     print(item)
...
{'k1': 0, '__id': 0}
{'k1': 1, '__id': 1}
{'k1': 2, '__id': 2}
>>> c1iter = c1.iterator()
>>> c1iter2 = c1.iterator()
>>> for item in c1iter:
...     print(item)
...
{'k1': 0, '__id': 0}
{'k1': 1, '__id': 1}
{'k1': 2, '__id': 2}
>>> iter1 = iter(c1iter)
>>> iter2 = iter(c1iter2)
>>> print(next(iter1))
{'k1': 0, '__id': 0}
>>> print(next(iter1))
{'k1': 1, '__id': 1}
>>> print(next(iter2))
{'k1': 0, '__id': 0}
>>> print(next(iter1))
{'k1': 2, '__id': 2}
>>> print(next(iter2))
{'k1': 1, '__id': 1}
>>> print(next(iter2))
{'k1': 2, '__id': 2}
>>> print(next(iter2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unqlite.pyx", line 1230, in unqlite.CollectionIterator.__next__
    raise StopIteration
StopIteration
>>>
```

**Comment by coleifer** [comment]
Awesome, thanks @anselor - that's a great idea for a testcase (independent iterators). I wrote it so that it would work but it should probably get some coverage.

**Comment by coleifer** [comment]
Tagged 0.9.1 and released.

**Comment by anselor** [comment]
Also, FWIW, I'm aware (as of about 4 days ago) that apparently 5 years ago the sqlite project added support for embedding and querying JSON in a table column. Unfortunately I've already gone pretty far down the path of using unqlite. All of my database interaction is pretty isolated so that I can easily swap out if needed so I plan on revisiting the choice of databases once I get to a stable point. 

Thanks for your help getting past this hump!
