### ISSUE TITLE
Collection reverse iterator

### ISSUE THREAD

**Issue by anselor** [coleifer/unqlite-python#59]
I was wondering if you had any insight into how I can iterate through the values in a collection in reverse insertion order. I don't see anything in the jx9 docs that does it. 

I did notice, however, that for each entry added to a collection, a new value is stored with the key of `collectionname_ID`. I was thinking a reverse iterator could be made by getting `last_record_id()` from the collection, creating a Cursor and seeking to `collectionname_lastid` and then calling `previous_entry` to seek backwards until it gets to the first value. 

Thanks

**Comment by coleifer** [comment]
This is not supported by unqlite as far as I can tell. Personally, I would strongly recommend considering using sqlite, which is actively being maintained and improved. Unqlite is seemingly not being maintained anymore.
