### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Dhanachandra** [coleifer/unqlite-python#62]
`unqlite.cpython-310-x86_64-linux-gnu.so: undefined symbol:  _PyGen_Send`

Python version: 3.10

**Comment by coleifer** [comment]
Try re-generating the C bindings:

```python
pip install cython
touch unqlite.pyx
python setup.py build
```

**Comment by Dhanachandra** [comment]
@coleifer The error is not still solved even after following yours steps.

**Comment by coleifer** [comment]
I'm not sure what to tell you, I just created a fresh virtualenv with Python 3.10 and ran the following:

```
pip install cython
git clone git@github.com:coleifer/unqlite-python 
cd unqlite-python
python setup.py build_ext -i  # build in current dir
python tests.py
```

All tests passed.
