### ISSUE TITLE
Cannot install unqlite 0.9.4 on Windows

### ISSUE THREAD

**Issue by sverzakov** [coleifer/unqlite-python#64]
I have been always able to pip install unqlite on Windows without any problems. However, 0.9.4 is complaining that pthresd.lib is not available. 0.9.3 is still can be pip installed. 

Probably some conditional define for pthread needed for Windows is missing?

Here is the pip output (adding --use-pep517 to command line did not help, by the way):

(py3.10) PS D:\py3.10\Scripts> pip install -U --force unqlite==0.9.4
Looking in indexes: https://pypi.org/simple
Collecting unqlite==0.9.4
  Using cached unqlite-0.9.4.tar.gz (579 kB)
  Preparing metadata (setup.py) ... done
Collecting Cython (from unqlite==0.9.4)
  Using cached Cython-0.29.36-py2.py3-none-any.whl (988 kB)
Building wheels for collected packages: unqlite
  Building wheel for unqlite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      D:\Tools\PVPythons\VirtEnvs\py3.10-dev\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_ext
      building 'unqlite' extension
      creating build
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\src
      "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DUNQLITE_ENABLE_THREADS=1 -ID:\Tools\PVPythons\VirtEnvs\py3.10-dev\include -ID:\Tools\PVPythons\Pythons\Python-3.10\include -ID:\Tools\PVPythons\Pythons\Python-3.10\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcsrc/unqlite.c /Fobuild\temp.win-amd64-cpython-310\Release\src/unqlite.obj
      unqlite.c
      "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DUNQLITE_ENABLE_THREADS=1 -ID:\Tools\PVPythons\VirtEnvs\py3.10-dev\include -ID:\Tools\PVPythons\Pythons\Python-3.10\include -ID:\Tools\PVPythons\Pythons\Python-3.10\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcunqlite.c /Fobuild\temp.win-amd64-cpython-310\Release\unqlite.obj
      unqlite.c
      creating C:\Users\s.verzakov\AppData\Local\Temp\pip-install-x95dapei\unqlite_403336b7eb424aeba9a40466f176fdf1\build\lib.win-amd64-cpython-310
      "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Tools\PVPythons\VirtEnvs\py3.10-dev\libs /LIBPATH:D:\Tools\PVPythons\Pythons\Python-3.10\libs /LIBPATH:D:\Tools\PVPythons\Pythons\Python-3.10 /LIBPATH:D:\Tools\PVPythons\VirtEnvs\py3.10-dev\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" pthread.lib /EXPORT:PyInit_unqlite build\temp.win-amd64-cpython-310\Release\src/unqlite.obj build\temp.win-amd64-cpython-310\Release\unqlite.obj /OUT:build\lib.win-amd64-cpython-310\unqlite.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\src\unqlite.cp310-win_amd64.lib
      LINK : fatal error LNK1181: cannot open input file 'pthread.lib'
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for unqlite
  Running setup.py clean for unqlite
Failed to build unqlite
ERROR: Could not build wheels for unqlite, which is required to install pyproject.toml-based projects

**Comment by coleifer** [comment]
`unqlite` started requiring `pthread` in 0.9.4, see 2269ec9007794f4d7aff426dff1521143375864c and the unqlite docs for `UNQLITE_ENABLE_THREADS` https://unqlite.org/c_api_const.html. I could probably make this conditional for windows users?

The doc seems to indicate that it's only needed on posix:

>Note that you must link UnQLite with the POSIX threads library under UNIX systems (i.e: -lpthread).

**Comment by coleifer** [comment]
I've just pushed a new version, 0.9.5, which should only include pthread on posix systems. Please comment if you still encounter problems and I'll reopen.

**Comment by sverzakov** [comment]
Thank you for the super fast fix!
