### ISSUE TITLE
Add Collection.update

### ISSUE THREAD

**Issue by goodevilgenius** [coleifer/unqlite-python#8]
UnQLite recently added [db_update_record](https://github.com/symisc/unqlite/commit/a529e00778e14d935dc82301beb327a8d9cdac77), so unqlite-python should add support for it as a method to the Collection object.

**Comment by coleifer** [comment]
Nice, it doesn't look like they've updated the release or amalgamation on their website, though. Last I heard they didn't really have plans to issue any new releases. So, while this is a cool feature that I want to add, I'm not sure how to go about it.
